name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: 서브모듈 최신화
        run: |
          git submodule update --remote          

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Gradle Wrapper로 빌드
        run: ./gradlew bootJar
        working-directory: .

      - name: 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          build-args: |
            SPRING_ACTIVE_PROFILE=dev

  deploy:  # 이 줄의 들여쓰기를 2칸으로 수정 (jobs 레벨과 같게)
    needs: build
    runs-on: self-hosted  # 대괄호 제거
    environment: prod
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: 서브모듈 최신화
        run: |
          git submodule update --remote

      - name: Docker Compose 파일 복사
        run: |
          sudo cp ./lv3-final-mission-submodule/docker/docker-compose.dev.yml /home/ubuntu/docker/docker-compose.yml

      - name: EC2 배포
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          cd /home/ubuntu/docker
          sudo docker-compose down
          sudo docker-compose up -d --build
          sudo docker image prune -f
